title: Yet Another Database Docs
email: hayter.eric@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  These are the documentation pages for Yet Another Database (yadb). The docs
  will include a wide variety of information including developer logs,
  architecture descriptions, etc...
baseurl: "/yadb-docs" # the subpath of your site, e.g. /blog
url: "https://www.erichayter.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  erichayter

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
